### ISSUE TITLE
Make start command doesn't start container in detach mode

### ISSUE THREAD

**Issue by ravbaba** [bodsch/docker-carbon-c-relay#4]
I've tried to run the container in detach mode but it exits with status 1.
Only way to make it works was to customise `run.sh` script.

I've notice it fails on this part:

```
  /usr/bin/relay \
    -f ${config_file} \
    -m \
    -l /dev/stdout
```
changing it to that fixes the issue:

```
  /usr/bin/relay \
    -f ${config_file}
```

**Comment by bodsch** [comment]
I will insert this in the next build.
thanks.
